main: net.michal.tools.WiksaTools
name: wiksa-tools
version: ${project.version}
description: plugin adds lot of commands for easyhc server
website: https://github.com/miszel-ini/wiksa-tools
author: michal
commands:
  linki:
    aliases: [links]
    description: server links
  premium:
    description: premium rank command
  pomoc:
    aliases: [help]
  invsee:
    permission: tools.wiksa.invsee
  endersee:
    permission: tools.wiksa.endersee